from enum import Enum

class RemissionEvents(str, Enum):
    INTEGRATED = "INTEGRATED"
    TRANSPORT_ARRIVAL = "TRANSPORT_ARRIVAL"
    PARTIAL_WITH_REJECTION = "PARTIAL_WITH_REJECTION"
    PARTIAL_COMPLETE = "PARTIAL_COMPLETE"
    COMPLETE = "COMPLETE"
    REJECTED = "REJECTED"